apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: https://b10e1b20a65c12d7bf5cbe2f46c83484.gr7.us-east-2.eks.amazonaws.com
      http:
        paths:
          - path: /auth/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-srv
                port:
                  number: 8001
          - path: /todos/?(.*)
            pathType: Prefix
            backend:
              service:
                name: todo-srv
                port:
                  number: 8001
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 80

